### ISSUE TITLE
Feature: Add function to read event history

### ISSUE THREAD

**Issue by OttoHollmann** [fdegier/JablotronPy#1]
I would like to use this library to read event history of my Jablotron device.

I found that there is endpoint `getHistory.json`, but I'm unable to get any data from it. Can you write function for obtaining history or advise me how to get specification/requirements of this endpoint? Then I could create PR with this feature.

**Comment by fdegier** [comment]
Awesome, I hadn't even realized people were already using this. I will take a look at this tomorrow and get back to you. Thank you for your interest and offer to help!

**Comment by fdegier** [comment]
So I tried to sniff the API today but I need Virtual box which is not available for Apple Silicon. I will need to get my Linux machine back online again before I can proceed. Are you able to do SSL sniffing? If so, you could quite easily get the correct parameters. If not, I'll do it later.
